# Level 2: The ndarray – Core Data Structure

The heart of NumPy is the `ndarray` (N-dimensional array). It's a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. This notebook covers how to create arrays, inspect their properties, and manage their data types.

In [1]:
import numpy as np

## 2.1 Creating Arrays

### From Python Lists

In [2]:
# 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

[1 2 3 4 5]


In [3]:
# 2D array (matrix)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


### From Ranges (`np.arange`)

In [4]:
# Similar to Python's range()
arr_range = np.arange(0, 10, 2) # (start, stop, step)
print(arr_range)

[0 2 4 6 8]


### Special Arrays

In [5]:
# Array of zeros
zeros_arr = np.zeros((2, 3)) # shape is a tuple
print("Zeros:\n", zeros_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Array of ones
ones_arr = np.ones((3, 2))
print("Ones:\n", ones_arr)

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# Array filled with a constant value
full_arr = np.full((2, 4), 7) # (shape, fill_value)
print("Full:\n", full_arr)

Full:
 [[7 7 7 7]
 [7 7 7 7]]


In [8]:
# Identity matrix
identity_matrix = np.eye(3) # size of one dimension
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2.2 Array Attributes

These attributes provide information about the array itself.

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)

Array:
 [[1 2 3]
 [4 5 6]]


In [10]:
print(f"Shape: {arr.shape}")
print(f"Number of dimensions (ndim): {arr.ndim}")
print(f"Total elements (size): {arr.size}")
print(f"Data type (dtype): {arr.dtype}")
print(f"Bytes per element (itemsize): {arr.itemsize}")
print(f"Total bytes (nbytes): {arr.nbytes}") # equal to size * itemsize

Shape: (2, 3)
Number of dimensions (ndim): 2
Total elements (size): 6
Data type (dtype): int64
Bytes per element (itemsize): 8
Total bytes (nbytes): 48


## 2.3 Data Types (`dtype`)

NumPy arrays must have all elements of the same data type. NumPy has a larger variety of numerical types than standard Python.

### Common Data Types
- `int8`, `int16`, `int32`, `int64`
- `uint8`, `uint16`, `uint32`, `uint64` (unsigned integers)
- `float16`, `float32`, `float64`
- `complex64`, `complex128`
- `bool`

### Explicit Casting on Creation

In [11]:
arr_float = np.array([1, 2, 3], dtype=np.float32)
print(arr_float)
print(f"Dtype: {arr_float.dtype}")

[1. 2. 3.]
Dtype: float32


### Type Conversion with `.astype()`

In [12]:
arr_int = np.array([1.1, 2.7, 3.5])
print(f"Original array (float): {arr_int}")

# Convert to integer type (truncates decimals)
arr_converted = arr_int.astype(np.int32)
print(f"Converted array (int): {arr_converted}")

Original array (float): [1.1 2.7 3.5]
Converted array (int): [1 2 3]


In [13]:
# You can also convert between other types, like to a boolean
arr_bool = np.array([0, 1, -1, 0, 5]).astype(bool)
print(f"Boolean array: {arr_bool}") # Zero becomes False, non-zero becomes True

Boolean array: [False  True  True False  True]
