# Level 3: Array Indexing & Slicing

Accessing and modifying subsets of data is a fundamental part of data analysis. NumPy offers rich and powerful indexing and slicing capabilities that are efficient and easy to use. A key concept to master here is the difference between a **view** and a **copy**.

In [1]:
import numpy as np

## 3.1 Indexing

### 1D Arrays

In [2]:
arr1d = np.arange(10, 20)
print(f"Array: {arr1d}")
print(f"First element: {arr1d[0]}")
print(f"Last element: {arr1d[-1]}")

Array: [10 11 12 13 14 15 16 17 18 19]
First element: 10
Last element: 19


### 2D Arrays (Matrices)

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:\n", arr2d)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# To access an element, use `arr[row, column]`
print(f"Element at row 0, col 1: {arr2d[0, 1]}")

Element at row 0, col 1: 2


In [5]:
# You can also use `arr[row][column]`, but the single-bracket method is more efficient.
print(f"Element at row 2, col 2: {arr2d[2][2]}")

Element at row 2, col 2: 9


### 3D and Higher-Dimensional Arrays

In [6]:
arr3d = np.arange(24).reshape(2, 3, 4) # 2 matrices, 3 rows, 4 columns
print("Array:\n", arr3d)

Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
# Access element in the 1st matrix, 2nd row, 3rd column
print(f"Element at (0, 1, 2): {arr3d[0, 1, 2]}")

Element at (0, 1, 2): 6


## 3.2 Slicing

Slicing allows you to select a range of elements. The syntax is `start:stop:step`.

In [8]:
print(f"Array: {arr1d}")
print(f"Elements from index 1 to 4: {arr1d[1:5]}")
print(f"Every other element: {arr1d[::2]}")
print(f"Reversed array: {arr1d[::-1]}")

Array: [10 11 12 13 14 15 16 17 18 19]
Elements from index 1 to 4: [11 12 13 14]
Every other element: [10 12 14 16 18]
Reversed array: [19 18 17 16 15 14 13 12 11 10]


### Multi-dimensional Slicing

In [9]:
print("Original Array:\n", arr2d)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Slice the first two rows and columns 1-2
sub_array = arr2d[0:2, 1:3]
print("Sub-array:\n", sub_array)

Sub-array:
 [[2 3]
 [5 6]]


In [11]:
# Select a single row
print("Row 1:", arr2d[1, :])

Row 1: [4 5 6]


In [12]:
# Select a single column
print("Column 2:", arr2d[:, 2])

Column 2: [3 6 9]


## 3.3 Views vs. Copies

This is one of the most important and potentially confusing aspects of NumPy.

- A **view** is a new array object that looks at the *same data* as the original array. Modifying a view will modify the original array.
- A **copy** is a new array object with its *own data*. Modifying a copy will **not** affect the original.

**Slicing an array creates a view.** This is done for performance reasons, to avoid copying large amounts of data.

In [13]:
arr = np.arange(10)
print(f"Original array: {arr}")

# Create a slice (which is a view)
arr_slice = arr[5:8]
print(f"Slice: {arr_slice}")

Original array: [0 1 2 3 4 5 6 7 8 9]
Slice: [5 6 7]


In [14]:
# Modify the slice
arr_slice[0] = 99
print(f"Modified slice: {arr_slice}")

Modified slice: [99  6  7]


In [15]:
# The original array is also modified!
print(f"Original array after modification: {arr}")

Original array after modification: [ 0  1  2  3  4 99  6  7  8  9]


### Creating a Copy
If you want an independent copy of a slice, you must use the `.copy()` method.

In [16]:
arr = np.arange(10)
print(f"Original array: {arr}")

# Create a copy of a slice
arr_copy = arr[5:8].copy()
print(f"Copy: {arr_copy}")

Original array: [0 1 2 3 4 5 6 7 8 9]
Copy: [5 6 7]


In [17]:
# Modify the copy
arr_copy[0] = 99
print(f"Modified copy: {arr_copy}")

Modified copy: [99  6  7]


In [18]:
# The original array is NOT affected
print(f"Original array after copy modification: {arr}")

Original array after copy modification: [0 1 2 3 4 5 6 7 8 9]
