# Level 4: Array Manipulation

Manipulating the structure of arrays is a common requirement in data processing. This notebook covers how to reshape, transpose, combine, and split NumPy arrays.

In [1]:
import numpy as np

## 4.1 Reshaping Arrays

### `.reshape()`
Changes the shape of an array without changing its data. The new shape must have the same number of total elements as the original.

In [2]:
arr = np.arange(12)
print(f"Original array (shape {arr.shape}):\n", arr)

Original array (shape (12,)):
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
reshaped_arr = arr.reshape(3, 4)
print(f"Reshaped array (shape {reshaped_arr.shape}):\n", reshaped_arr)

Reshaped array (shape (3, 4)):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


You can use `-1` in one of the dimensions, and NumPy will automatically infer the correct size.

In [4]:
arr.reshape(2, -1) # Infers a shape of (2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### `.ravel()` (Flattening)
Returns a new 1D array (a view if possible, otherwise a copy).

In [5]:
print("Original array:\n", reshaped_arr)
print("Raveled array:", reshaped_arr.ravel())

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 4.2 Transpose & Swap Axes

### `.T` or `.transpose()`

In [6]:
arr = np.arange(6).reshape(2, 3)
print("Original array:\n", arr)

Original array:
 [[0 1 2]
 [3 4 5]]


In [7]:
print("Transposed array:\n", arr.T)

Transposed array:
 [[0 3]
 [1 4]
 [2 5]]


### `.swapaxes()`
For higher-dimensional arrays, you can swap any two axes.

In [8]:
arr3d = np.arange(24).reshape(2, 3, 4)
print(f"Original shape: {arr3d.shape}")

# Swap axis 1 and 2
swapped = arr3d.swapaxes(1, 2)
print(f"Swapped shape: {swapped.shape}")

Original shape: (2, 3, 4)
Swapped shape: (2, 4, 3)


## 4.3 Adding/Removing Dimensions

### `np.newaxis`
Used to increase the dimension of an existing array by one.

In [9]:
arr = np.arange(4)
print(f"Original array (shape {arr.shape}): {arr}")

# Add a new axis to make it a column vector
col_vec = arr[:, np.newaxis]
print(f"Column vector (shape {col_vec.shape}):\n{col_vec}")

# Add a new axis to make it a row vector
row_vec = arr[np.newaxis, :]
print(f"Row vector (shape {row_vec.shape}):\n{row_vec}")

Original array (shape (4,)): [0 1 2 3]
Column vector (shape (4, 1)):
[[0]
 [1]
 [2]
 [3]]
Row vector (shape (1, 4)):
[[0 1 2 3]]


### `np.expand_dims()` & `np.squeeze()`
`expand_dims` is a function-based way to do the same as `newaxis`. `squeeze` removes single-dimensional entries from the shape of an array.

In [10]:
expanded = np.expand_dims(arr, axis=1)
print(f"Expanded shape: {expanded.shape}")

squeezed = np.squeeze(expanded)
print(f"Squeezed shape: {squeezed.shape}")

Expanded shape: (4, 1)
Squeezed shape: (4,)


## 4.4 Concatenation & Splitting

### `np.concatenate()`

In [11]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [12]:
# Concatenate along the first axis (rows)
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
# Concatenate along the second axis (columns) - shapes must match
np.concatenate((a, a), axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

### `vstack`, `hstack`, `dstack`
These are convenient helpers for common concatenation tasks.

In [14]:
print("vstack (vertical):\n", np.vstack((a, b)))
print("\nhstack (horizontal):\n", np.hstack((a, a)))

vstack (vertical):
 [[1 2]
 [3 4]
 [5 6]]

hstack (horizontal):
 [[1 2 1 2]
 [3 4 3 4]]


### `np.split()`
Splits an array into multiple sub-arrays.

In [15]:
arr = np.arange(9)
print("Original array:", arr)

# Split into 3 equal-sized sub-arrays
np.split(arr, 3)

Original array: [0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [16]:
# Split at specified positions
np.split(arr, [3, 5]) # Split at index 3 and 5

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8])]

Like concatenation, there are helpers `hsplit` and `vsplit`.