# Level 5: Vectorization & Broadcasting

Vectorization and broadcasting are the two most important concepts for writing fast and efficient NumPy code. They allow you to perform complex operations on arrays without writing slow Python loops.

In [13]:
import numpy as np

## 5.1 Vectorized Operations

Vectorization is the process of applying an operation to all elements of an array at once. These operations are performed in highly optimized C code, making them much faster than iterating in Python.

In [14]:
arr = np.arange(5)
print(f"Original array: {arr}")

Original array: [0 1 2 3 4]


In [15]:
# All standard arithmetic operations are vectorized
print(f"arr + 5 = {arr + 5}")
print(f"arr * 2 = {arr * 2}")
print(f"arr ** 2 = {arr ** 2}")

arr + 5 = [5 6 7 8 9]
arr * 2 = [0 2 4 6 8]
arr ** 2 = [ 0  1  4  9 16]


### Universal Functions (ufuncs)
NumPy provides a large library of ufuncs, which are functions that operate on ndarrays in an element-by-element fashion. They are the core of NumPy's vectorized nature.

In [16]:
print(f"Square root: {np.sqrt(arr)}")
print(f"Exponential: {np.exp(arr)}")
print(f"Sine: {np.sin(arr)}")

Square root: [0.         1.         1.41421356 1.73205081 2.        ]
Exponential: [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
Sine: [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


## 5.2 Broadcasting

Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations. It describes how NumPy treats arrays with different shapes during arithmetic operations.

### The Rules of Broadcasting
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., rightmost) dimensions and works its way left. Two dimensions are compatible when
1. they are equal, or
2. one of them is 1.

If these conditions are not met, a `ValueError` is thrown. If the two arrays have a different number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

### Example 1: Simple Broadcasting

In [17]:
a = np.arange(6).reshape(2, 3) # Shape (2, 3)
b = 100 # A scalar (can be thought of as shape (1,))

# The scalar is 'broadcast' across the array
print(a + b)

[[100 101 102]
 [103 104 105]]


### Example 2: Broadcasting a 1D array to a 2D array

In [18]:
matrix = np.arange(12).reshape(3, 4) # Shape (3, 4)
vector = np.array([10, 20, 30, 40])  # Shape (4,)

print("Matrix (3, 4):\n", matrix)
print("\nVector (4,):\n", vector)

# How it works:
# matrix shape: (3, 4)
# vector shape: (   4) -> Padded to (1, 4)
# Result shape: (3, 4)
# The vector is stretched to match the matrix's shape.

print("\nResult:\n", matrix + vector)

Matrix (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Vector (4,):
 [10 20 30 40]

Result:
 [[10 21 32 43]
 [14 25 36 47]
 [18 29 40 51]]


### Example 3: When Broadcasting Fails

In [19]:
vector_bad = np.array([10, 20, 30]) # Shape (3,)

try:
    matrix + vector_bad
except ValueError as e:
    print(f"Error: {e}")
    print("\nThis fails because the trailing dimensions (4 and 3) are not equal, and neither is 1.")

Error: operands could not be broadcast together with shapes (3,4) (3,) 

This fails because the trailing dimensions (4 and 3) are not equal, and neither is 1.


### Fixing a Broadcasting Error
To fix the above, you can reshape the vector to have a compatible shape.

In [20]:
vector_fixed = vector_bad.reshape(3, 1) # Shape (3, 1)

# How it works now:
# matrix shape:      (3, 4)
# vector_fixed shape: (3, 1)
# Result shape:      (3, 4)
# The vector is stretched across both dimensions.

print("Matrix (3, 4):\n", matrix)
print("\nFixed Vector (3, 1):\n", vector_fixed)
print("\nResult:\n", matrix + vector_fixed)

Matrix (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Fixed Vector (3, 1):
 [[10]
 [20]
 [30]]

Result:
 [[10 11 12 13]
 [24 25 26 27]
 [38 39 40 41]]


## 5.3 Comparison & Logical Operations

These are also vectorized and return boolean arrays. These boolean arrays are crucial for conditional selection (covered in the next level).

In [21]:
arr = np.arange(10)
print(f"Array: {arr}")

Array: [0 1 2 3 4 5 6 7 8 9]


In [22]:
# Comparison operations
print(f"arr > 5: {arr > 5}")
print(f"arr == 3: {arr == 3}")

arr > 5: [False False False False False False  True  True  True  True]
arr == 3: [False False False  True False False False False False False]


### Combining Logical Conditions
Use `&` for AND and `|` for OR. Do not use the Python keywords `and` and `or`.

In [23]:
(arr > 3) & (arr < 8)

array([False, False, False, False,  True,  True,  True,  True, False,
       False])

NumPy also has logical ufuncs, which can be more explicit.

In [24]:
np.logical_and(arr > 3, arr < 8)

array([False, False, False, False,  True,  True,  True,  True, False,
       False])