# Level 6: Indexing & Selection (Advanced)

Beyond basic slicing, NumPy offers more sophisticated ways to select data. These methods allow for filtering and selecting elements based on conditions (Boolean indexing) or specific lists of indices (fancy indexing). These techniques are central to effective data manipulation.

In [1]:
import numpy as np

## 6.1 Boolean Indexing

Boolean indexing uses an array of boolean values to select elements from another array. The boolean array must have the same shape as the dimension it's indexing.

In [2]:
arr = np.arange(10)
print(f"Original array: {arr}")

Original array: [0 1 2 3 4 5 6 7 8 9]


In [3]:
# Create a boolean condition
condition = arr > 5
print(f"Boolean mask:   {condition}")

Boolean mask:   [False False False False False False  True  True  True  True]


In [4]:
# Use the boolean mask to filter the array
# This returns a 1D array of all elements where the mask was True
print(f"Filtered array: {arr[condition]}")

Filtered array: [6 7 8 9]


This is more commonly written in a single line:

In [5]:
arr[arr % 2 == 0] # Select only even numbers

array([0, 2, 4, 6, 8])

### Combining Conditions

In [6]:
# Use & for AND, | for OR
arr[(arr > 3) & (arr < 8)]

array([4, 5, 6, 7])

### Replacing Values with Boolean Indexing

In [7]:
# Replace all values greater than 5 with 0
arr[arr > 5] = 0
print(arr)

[0 1 2 3 4 5 0 0 0 0]


**Important:** Unlike slicing, boolean indexing always returns a **copy** of the data, not a view.

## 6.2 Fancy Indexing

Fancy indexing is a term for indexing arrays using other arrays (or lists) of integers. This allows you to select arbitrary elements.

In [8]:
arr = np.arange(100, 110)
print(f"Original array: {arr}")

Original array: [100 101 102 103 104 105 106 107 108 109]


In [9]:
# Select elements at indices 0, 2, and 4
indices = [0, 2, 4]
arr[indices]

array([100, 102, 104])

### Fancy Indexing in 2D

In [10]:
arr2d = np.arange(12).reshape(3, 4)
print("Array:\n", arr2d)

Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
# Select specific rows
arr2d[[0, 2]] # Selects row 0 and row 2

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [12]:
# To select specific elements, pass a tuple of index arrays: `arr[rows, cols]`
# This selects the elements at (0, 1) and (2, 3)
arr2d[[0, 2], [1, 3]]

array([ 1, 11])

**Important:** Fancy indexing, like boolean indexing, also returns a **copy** of the data, not a view.

## 6.3 `np.where()`

`np.where()` is a powerful function that acts as a vectorized `if-else`.

### Form 1: `np.where(condition, x, y)`
Returns elements from `x` where `condition` is True, and elements from `y` where it is False.

In [13]:
arr = np.arange(10)
print(f"Original array: {arr}")

# Replace all odd numbers with -1 and keep even numbers as they are
np.where(arr % 2 == 0, arr, -1)

Original array: [0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Form 2: `np.where(condition)`
When called with only a condition, `np.where()` returns a tuple of indices where the condition is True. This is very useful for locating elements.

In [14]:
indices = np.where(arr > 5)
print(f"Indices where arr > 5: {indices}")

Indices where arr > 5: (array([6, 7, 8, 9]),)


In [15]:
# You can then use these indices to select the elements
arr[indices]

array([6, 7, 8, 9])

## 6.4 `np.select()`

`np.select()` is used for choosing elements from a list of choices based on a list of conditions. It's like a vectorized `if-elif-else` chain.

In [16]:
arr = np.arange(10)
print(f"Original array: {arr}")

conditions = [
    arr < 3,         # Condition 1
    arr > 6,         # Condition 2
    (arr >=3) & (arr <=6) # Condition 3
]

choices = [
    -1,              # Value if condition 1 is True
    1,               # Value if condition 2 is True
    0                # Value if condition 3 is True
]

# The default value is 0 if no conditions are met
np.select(conditions, choices, default=99)

Original array: [0 1 2 3 4 5 6 7 8 9]


array([-1, -1, -1,  0,  0,  0,  0,  1,  1,  1])