# Level 7: Mathematical & Statistical Functions

NumPy provides a vast library of mathematical, statistical, and linear algebra functions. These functions are all ufuncs, meaning they are highly optimized and operate element-wise or on entire arrays.

In [1]:
import numpy as np

## 7.1 Basic Mathematical & Statistical Functions

In [2]:
arr = np.arange(1, 10).reshape(3, 3)
print("Array:\n", arr)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(f"Sum of all elements: {np.sum(arr)}")
print(f"Mean of all elements: {np.mean(arr)}")
print(f"Standard deviation: {np.std(arr):.2f}")
print(f"Variance: {np.var(arr):.2f}")

Sum of all elements: 45
Mean of all elements: 5.0
Standard deviation: 2.58
Variance: 6.67


In [4]:
print(f"Minimum value: {np.min(arr)}")
print(f"Maximum value: {np.max(arr)}")

Minimum value: 1
Maximum value: 9


`argmin` and `argmax` return the *index* of the minimum and maximum values, respectively.

In [5]:
print(f"Index of minimum value: {np.argmin(arr)}") # Index in the flattened array
print(f"Index of maximum value: {np.argmax(arr)}")

Index of minimum value: 0
Index of maximum value: 8


## 7.2 Axis Operations

Many of these functions can be applied along a specific axis.
- `axis=0`: Perform the operation down the columns.
- `axis=1`: Perform the operation across the rows.

In [6]:
print("Array:\n", arr)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Sum down the columns (axis=0)
print(f"Sum of columns: {arr.sum(axis=0)}")

Sum of columns: [12 15 18]


In [8]:
# Sum across the rows (axis=1)
print(f"Sum of rows: {arr.sum(axis=1)}")

Sum of rows: [ 6 15 24]


## 7.3 Rounding & Trigonometry

In [9]:
arr_float = np.array([1.23, 4.56, 7.89])
print(f"Rounding: {np.round(arr_float, 1)}")
print(f"Floor: {np.floor(arr_float)}")
print(f"Ceiling: {np.ceil(arr_float)}")

Rounding: [1.2 4.6 7.9]
Floor: [1. 4. 7.]
Ceiling: [2. 5. 8.]


In [10]:
angles = np.array([0, np.pi/2, np.pi])
print(f"Sine: {np.sin(angles)}")

Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


## 7.4 Exponents & Logarithms

In [11]:
arr = np.arange(1, 5)
print(f"Array: {arr}")
print(f"e^arr: {np.exp(arr)}")
print(f"ln(arr): {np.log(arr)}")
print(f"log10(arr): {np.log10(arr)}")

Array: [1 2 3 4]
e^arr: [ 2.71828183  7.3890561  20.08553692 54.59815003]
ln(arr): [0.         0.69314718 1.09861229 1.38629436]
log10(arr): [0.         0.30103    0.47712125 0.60205999]


## 7.5 Linear Algebra (Basics)

NumPy's `linalg` submodule contains a wide range of linear algebra functions.

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])

### Dot Product (`.dot()`)

In [13]:
# Vector-vector dot product
np.dot(v, v)

np.int64(181)

In [14]:
# Matrix-vector product
np.dot(A, v)

array([29, 67])

### Matrix Multiplication (`@` or `np.matmul()`)

In [15]:
# The @ operator is the recommended way for matrix multiplication
A @ B

array([[19, 22],
       [43, 50]])

In [16]:
# Equivalent to np.matmul
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

### Inverse, Determinant, Eigenvalues

In [17]:
# Matrix Inverse
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
# Determinant
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A:.1f}")

Determinant of A: -2.0


In [19]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
