# Level 8: Random Number Generation

Generating random numbers is essential for a wide range of applications, including simulations (like Monte Carlo methods), creating sample data, and initializing parameters in machine learning models. NumPy provides a powerful and flexible module for this: `np.random`.

In [1]:
import numpy as np

## 8.1 The `np.random` Module (Legacy)

For a long time, the standard way to generate random numbers was using functions directly from `np.random`. While still common in older code, the new generator system (covered next) is now recommended.

In [2]:
# Random floats from a uniform distribution over [0, 1)
print("rand(3, 3):\n", np.random.rand(3, 3))

rand(3, 3):
 [[0.83511441 0.68101813 0.09162303]
 [0.95012877 0.71826067 0.28988857]
 [0.43737603 0.4482914  0.22703401]]


In [3]:
# Random floats from a standard normal distribution (mean=0, variance=1)
print("\nrandn(3, 3):\n", np.random.randn(3, 3))


randn(3, 3):
 [[-0.48527142 -0.18440729 -1.16294339]
 [-0.22617593 -0.21253698  1.93114058]
 [-0.29010973 -0.62703935 -1.09701104]]


In [4]:
# Random integers from a given range [low, high)
print("\nrandint(0, 10, size=5):", np.random.randint(0, 10, size=5))


randint(0, 10, size=5): [0 3 8 7 1]


## 8.2 Seeding for Reproducibility

When you need your 'random' numbers to be the same every time you run your code (e.g., for testing or to ensure a machine learning experiment is reproducible), you must set a **seed**. The seed initializes the random number generator to a deterministic state.

In [5]:
# Without a seed, the numbers are different each time
print("Run 1:", np.random.rand(3))
print("Run 2:", np.random.rand(3))

Run 1: [0.70048535 0.73812769 0.65120468]
Run 2: [0.48318711 0.52855215 0.11883837]


In [6]:
# With a seed, the sequence is the same
np.random.seed(42)
print("\nRun 1 with seed:", np.random.rand(3))

np.random.seed(42)
print("Run 2 with seed:", np.random.rand(3))


Run 1 with seed: [0.37454012 0.95071431 0.73199394]
Run 2 with seed: [0.37454012 0.95071431 0.73199394]


**Problem with `np.random.seed()`:** It sets the seed for a single, global random number generator. This can cause issues if different parts of your code (or libraries you use) also set the global seed.

## 8.3 The New Random Generator (Recommended)

Starting with NumPy 1.17, a new, more robust system for random number generation was introduced. The recommended practice is to create a dedicated `Generator` instance and call its methods. This avoids the problems of a global state.

### Creating a Generator
You create a generator instance using `np.random.default_rng()`. You can pass a seed to it for reproducibility.

In [7]:
rng = np.random.default_rng(seed=42)
print(rng)

Generator(PCG64)


### Using the Generator
The generator object has methods for creating random numbers. These methods often have more intuitive names than the legacy versions.

In [8]:
# Random integers
print("Integers:", rng.integers(low=0, high=10, size=5))

Integers: [0 7 6 4 4]


In [9]:
# Random floats from a uniform distribution
print("\nUniform floats:\n", rng.uniform(low=0, high=1, size=(2, 2)))


Uniform floats:
 [[0.69736803 0.09417735]
 [0.97562235 0.7611397 ]]


In [10]:
# Random floats from a normal distribution
print("\nNormal floats:\n", rng.normal(loc=0, scale=1, size=(2, 2))) # loc=mean, scale=std dev


Normal floats:
 [[-0.31624259 -0.01680116]
 [-0.85304393  0.87939797]]


In [11]:
# Randomly choose from an array
choices = np.array(['A', 'B', 'C', 'D'])
print("\nChoices:", rng.choice(choices, size=5))


Choices: ['D' 'A' 'D' 'D' 'C']


In [12]:
# Shuffle an array in-place
arr_to_shuffle = np.arange(10)
rng.shuffle(arr_to_shuffle)
print("\nShuffled array:", arr_to_shuffle)


Shuffled array: [1 0 5 4 8 9 7 2 3 6]


By creating and passing around `rng` objects, your code becomes more modular, predictable, and free from the side effects of a global random state.